### ISSUE TITLE
"ERROR: UndefVarError: sem not defined"

### ISSUE THREAD

**Issue by carlomontec** [piever/GroupedErrors.jl#20]
Cant run the tutorial, the function sem is not recognized.

"ERROR: UndefVarError: sem not defined"

Should I add another package maybe?

Best greetings.

**Comment by piever** [comment]
Ups, `sem` should be in `StatsBase`. Just run `using StatsBase` at the beginning and it should work: I'll update the README.

**Comment by carlomontec** [comment]
Thanks!

Thanks a lot for the package, I am about to use it a lot... 
 I think you will hear from me soon. 🤓
